=== jmmenah/markup-languages/DTD/Ejercicios-DTD-1/ej4.dtd
<!ELEMENT Biblioteca (Libro*)>
<!ELEMENT Libro (Titulo|Autor|Editado)*>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Autor (#PCDATA)>
<!ELEMENT Editado EMPTY>

<!ATTLIST Libro ISBN CDATA #REQUIRED>
<!ATTLIST Libro recomendar (si|no) #IMPLIED>
<!ATTLIST Editado editorial CDATA #IMPLIED>
<!ATTLIST Editado aÃ±o CDATA #IMPLIED>

=== jmmenah/markup-languages/DTD/Ejercicios-DTD-1/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca SYSTEM "ej4.dtd">
<Biblioteca>
  <Libro ISBN="_978-84-206-7415-5" recomendar="si">
    <Titulo>Mi familia y otros animales</Titulo>
    <Autor>Gerald Durrell</Autor>
    <Editado editorial="ALIANZA EDITORIAL" año="2010"/>
  </Libro>
  <Libro ISBN="_978-84-670-2154-7" recomendar="si">
    <Titulo>Cantar de mio Cid</Titulo>
    <Editado editorial="Espasa Calpe" año="2006"/>
  </Libro>
  <Libro ISBN="_978-84-667-9295-0">
    <Titulo>Cuentos de los hermanos Grimm</Titulo>
    <Autor>Jacob Grimm</Autor>
    <Autor>Wilhelm Grimm</Autor>
    <Editado editorial="Anaya"/>
  </Libro>
  <Libro ISBN="_978-84-322-2858-2" recomendar="no">
    <Titulo>Maldito karma</Titulo>
    <Autor>David Safier</Autor>
  </Libro>
</Biblioteca>
