=== jmmenah/markup-languages/DTD/Ejercicios-DTD-2/ej4.dtd
<!ELEMENT menu (denominacion,precio,fecha?,entrantes+,primero+,postre+)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT entrantes (#PCDATA)>
<!ELEMENT primero (#PCDATA)>
<!ELEMENT postre (#PCDATA)>

=== jmmenah/markup-languages/DTD/Ejercicios-DTD-2/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "ej4.dtd">
<menu>
  <denominacion> Menu del día</denominacion>
  <precio>8,50</precio>
  <fecha>12/04/2010</fecha>
  <entrantes> Sepia a la plancha</entrantes>
  <primero>Lubina al horno</primero>
  <primero>Solomillo con patatas</primero>
  <postre> Flan con nata</postre>
</menu>
