=== jmmenah/markup-languages/DTD/Ejercicios-DTD-2/ej5.dtd
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (nfra,fecha,cliente,descuento?,producto+)>
<!ELEMENT nfra (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cliente (codigo|(nif,nombre,direccion))>
<!ELEMENT descuento (#PCDATA)>
<!ELEMENT producto (codpro,descripcion,cantidad,precio)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT codpro (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== jmmenah/markup-languages/DTD/Ejercicios-DTD-2/ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "ej5.dtd">
<facturas>
  <factura>
    <nfra>001</nfra>
    <fecha>02/02/2020</fecha>
    <cliente>
      <codigo>77854</codigo>
    </cliente>
    <producto>
      <codpro>2000</codpro>
      <descripcion>Agua</descripcion>
      <cantidad>1</cantidad>
      <precio>0.25€</precio>
    </producto>
  </factura>
  <factura>
    <nfra>002</nfra>
    <fecha>02/02/2020</fecha>
    <cliente>
      <nif>77358410B</nif>
      <nombre>Juan Moral Blanca</nombre>
      <direccion>Calle Llana nº3</direccion>
    </cliente>
    <descuento>5%</descuento>
    <producto>
      <codpro>2000</codpro>
      <descripcion>Coca-Cola</descripcion>
      <cantidad>1</cantidad>
      <precio>1.5€</precio>
    </producto>
  </factura>
</facturas>
