=== jmmenah/markup-languages/XMLSchema/DTD-XSD/ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listaalumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="ap1"/>
              <xs:element type="xs:string" name="ap2" minOccurs="0"/>
              <xs:element type="xs:byte" name="edad" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="dni" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:date" name="curso"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jmmenah/markup-languages/XMLSchema/DTD-XSD/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaalumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" curso="1999-10-20" xsi:noNamespaceSchemaLocation="ej1.xsd">
  <!--DNI atributo obligatorio-->
  <alumno dni="5667545Z">
    <!--Nombre y ap1 obligatorios-->
    <nombre>Jose</nombre>
    <ap1>Sanchez</ap1>
  </alumno>
  <alumno dni="5778221D">
    <nombre>Andres</nombre>
    <ap1>Ruiz</ap1>
    <!--Ap2 y edad son optativos-->
    <ap2>Ruiz</ap2>
    <!--La edad debe ser positiva-->
    <edad>25</edad>
  </alumno>
</listaalumnos>
