=== jmmenah/markup-languages/DTD/examen-dtd/ej2.dtd
<!ELEMENT catalogo (producto+)>
<!ELEMENT producto (especificacion+,opcion?,precio+,nota?)>
<!ELEMENT especificacion (#PCDATA)>
<!ELEMENT opcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT nota (#PCDATA)>

<!ATTLIST producto nombre CDATA #IMPLIED>
<!ATTLIST producto categoria (herramienta|mesa|tienda-profesional) "herramienta">
<!ATTLIST producto numpart NMTOKEN #IMPLIED>
<!ATTLIST producto fabrica (Valladolid|Palencia|Leon) "Valladolid">
<!ATTLIST producto inventario (enstock|bajoorden|nodisponible) "enstock">
<!ATTLIST especificacion peso CDATA #IMPLIED>
<!ATTLIST especificacion potencia CDATA #REQUIRED>
<!ATTLIST opcion adaptador (incluido|opcional |noincluido) "incluido">
<!ATTLIST precio moneda CDATA "euros">
<!ATTLIST precio gastodeenvio CDATA #IMPLIED>

=== jmmenah/markup-languages/DTD/examen-dtd/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "ej2.dtd">
<catalogo>
  <producto nombre="cafetera" categoria="mesa" numpart="1" fabrica="Leon" inventario="bajoorden">
    <especificacion peso="10kg" potencia="50W">Basica</especificacion>
    <opcion adaptador="opcional">Opcion 1</opcion>
    <precio moneda="dolares">20</precio>
    <nota>Seminuevo</nota>
  </producto>
  <producto nombre="lavadora">
    <especificacion potencia="200W">5kg</especificacion>
    <especificacion potencia="250W">7kg</especificacion>
    <precio moneda="dolares">180</precio>
    <precio>175</precio>
  </producto>
</catalogo>
