=== jmmenah/markup-languages/DTD/examen-dtd/ej3.dtd
<!ELEMENT song (title,composers+,producers+,publiser,artists+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT composers (composer+)>
<!ELEMENT producers (producer+)>
<!ELEMENT publiser (#PCDATA)>
<!ELEMENT artists (artist+)>
<!ELEMENT composer (nombre,apellidos)>
<!ELEMENT producer (nombre,apellidos)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ATTLIST song length NMTOKEN #REQUIRED>
<!ATTLIST song anio NMTOKEN #IMPLIED>

=== jmmenah/markup-languages/DTD/examen-dtd/ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE song SYSTEM "ej3.dtd">
<song length="6:20" anio="1978">
  <title>Hot Cop</title>
  <composers>
    <composer>
      <nombre>Henry</nombre>
      <apellidos>Beolo</apellidos>
    </composer>
  </composers>
  <producers>
    <producer>
      <nombre>Jacques</nombre>
      <apellidos>Morali</apellidos>
    </producer>
  </producers>
  <publiser>PolyGram</publiser>
  <artists>
    <artist>Village People</artist>
  </artists>
</song>
