=== jmmenah/markup-languages/DTD/examen-dtd/ej4.dtd
<!ELEMENT autoescuela (alumno+,profesor+,coche+)>
<!ELEMENT alumno (nif,nombre,direccion)>
<!ELEMENT profesor (nif,nombre,direccion,horario)>
<!ELEMENT coche (matricula,modelo,marca)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT horario (dia+,hora+)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

<!ATTLIST alumno codigo ID #REQUIRED>
<!ATTLIST profesor codigo ID #REQUIRED>
<!ATTLIST coche codigo ID #REQUIRED>
<!ATTLIST alumno fase (teorico|practicas) #REQUIRED>
<!ATTLIST alumno profesort IDREF #REQUIRED>
<!ATTLIST alumno profesorp1 IDREF #REQUIRED>
<!ATTLIST alumno profesorp2 IDREF #IMPLIED>
<!ATTLIST alumno profesorp3 IDREF #IMPLIED>
<!ATTLIST alumno coche IDREF #REQUIRED>

=== jmmenah/markup-languages/DTD/examen-dtd/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE autoescuela SYSTEM "ej4.dtd">
<autoescuela>
  <alumno codigo="A1" fase="practicas" profesort="P1" profesorp1="P2" coche="C1">
<nif>78541269B</nif>
<nombre>Juan Moral</nombre>
<direccion>Calle Llana 2</direccion>  
  </alumno>
  <profesor codigo="P1">
<nif>45912587N</nif>
<nombre>Antonio Ruiz</nombre>
<direccion>Calle Agua 7</direccion>  
<horario>
  <dia>Lunes a Viernes</dia>
  <hora>16-20</hora>
</horario>
  </profesor>
  <profesor codigo="P2">
<nif>14962574F</nif>
<nombre>Maria Molina</nombre>
<direccion>Calle Madrid 4</direccion>
<horario>
  <dia>Lunes</dia>
  <hora>16-20</hora>
</horario>  
  </profesor>
  <coche codigo="C1">
<matricula>1569JVG</matricula>
<modelo>Renault</modelo>
<marca>Megane</marca>  
  </coche>
</autoescuela>
